### ISSUE TITLE
Precision issue when moving stick left or right

### ISSUE THREAD

**Issue by freezir12** [RightRudderLeftStick/OpenSource-VeryBigStick#5]
First: thank you for this design, exactly what i was looking for! 
I just assembled all the printed parts and after checking properly i recognized that there is a kinda lot of play on pitch movement. I can move the stick approximately 2 milimeters left and right without resistance before the CAMs start to move. Yaw axis is fine, there is no play.

I have moved each CAM mounting hole in the Pitchframe_Pillowblock 3mm to the outside (77mm distance between center of the holes) in hope this creates a better position of the bearings between the CAMs.

I will print and test tomorrow. I hope i did not increase the distance too much.

(Parts printed in ABS+ on a calibrated printer)

**Comment by RightRudderLeftStick** [comment]
Thats odd, the cams should always close up to take up slack.

Is the play in the second stage from the base? It could actually be the holes for the 6003 bearings are oversized and its slopping there. If there is movement there you can try running electrical or kapton tape to make it a snug fit

![fit_pillowblock](https://github.com/RightRudderLeftStick/OpenSource-VeryBigStick/assets/121038338/d5f7acc2-4dee-4ec4-9706-289c631a315b)


Could you record a video of it operating?

**Comment by freezir12** [comment]
Thx for your quick reply! 
The holes for the 6003 bearing is not the cause of that issue. The bearings fit snug, but to be sure i added some tape to make them fit even more tight. The issue still persists. 
In attached gif1 you can see the play of the yaw axis. In comparison you can see how well the pitch axis works in gif2.
In the attached picture i marked the positioning of bearings and CAMs what i think is the cause of the issue.
I still have black tape around the bearings (i tried to close the gap and make it more tight, do not be confused :) )
Your thoughts are much appreciated! :) 


![gif1](https://github.com/RightRudderLeftStick/OpenSource-VeryBigStick/assets/62761767/135fea79-2dc3-4008-8121-b97ae7b5357f)
![gif2](https://github.com/RightRudderLeftStick/OpenSource-VeryBigStick/assets/62761767/adbf05d6-87b9-4ea4-8b42-b5f8610571c8)
![issue](https://github.com/RightRudderLeftStick/OpenSource-VeryBigStick/assets/62761767/0e912c06-3763-4d77-a9d5-72d23d507bf4)

**Comment by RightRudderLeftStick** [comment]
Thats very odd. Is there anything preventing the dual cams from moving upwards in the neutral position? You are using the medium or hard cams?

Going to rack my brain on this for awhile, both axis have the same geometry for the roller in relationship to the cams pivot points, so they should behave the same with the same cam profile

**Comment by freezir12** [comment]
> Thats very odd. Is there anything preventing the dual cams from moving upwards in the neutral position? You are using the medium or hard cams?
> 
> Going to rack my brain on this for awhile, both axis have the same geometry for the roller in relationship to the cams pivot points, so they should behave the same with the same cam profile

I used the medium cams for pitch and yaw. 
The cams are pushing upwards against the bearings, i would consider this "neutral position". So no, nothing prevents them from going to neutral position. But from my understandig this is the issue: the cams are pushing upwards against the bearings, but not enough sideways to force the bearings to center. 

I checked your Fusion files and realized that the cams pivot point distance is the same for yaw and pitch axis so i was wondering  about the different behaviour too. Maybe the bearings pivot points screws moved a bit inside while screwing them into the plate, but i do not think that they moved that much inside to cause that issue. 


I will print the adjusted  Pitchframe_Pillowblock  this evening (should be done by 7pm/8pm and i will let you know if behaviour improved. Thx for your time! :)

**Comment by RightRudderLeftStick** [comment]
Looking at the top edge of the two cams, does it look crooked, like the M8x35mm are not perfectly straight? I also am wondering with ABS if there is some dimension that's shrunk, either on the pillowblock or the cams themselves.

**Comment by freezir12** [comment]
There is definetly something crooked but very hard to tell right now if it is the cams on the bearings, the screws or the pillow plate. I do not think it is because of shrinkage as all the cams are printed in the same ABS. I guess i will print the pillow plate in PETG after some further research. Going to post updates around 8pm/9pm.

Edit:
Maybe i will not able to provide any news today. Had some huge issues tuning my PETG. Printing a new Cam now for testing.

**Comment by freezir12** [comment]
Updates:
I found out that the cams did not fit snug with their bearings. That is were the crooked cams came from (pillow plate and screws are fine)
Printing them in PETG did not change anything on the play on the yaw axis movement.
I also printed new cams with their holes put 0.6mm inside (in direction where the roller bearing is). This just removed a little bit of play (0,3mm) but changed the overall behaviour/movement of the cams so i realized this idea is on the wrong path.

The solution for me was to print two stripes in ABS with the following dimensions: 
- height: 0,4mm
- wide: 8mm (thickness of the cams)
- length: 40mm  (cutted them to length as i needed it)
Then i used them to fill the gap (carefully positioning for a perfect fit - no stick wiggle) between cams and roller bearings and melted the stripes on to the cams with acetone (printed new bearings with snug fit in ABS before) as seen on the picture:
![IMG_4283](https://github.com/RightRudderLeftStick/OpenSource-VeryBigStick/assets/62761767/c07892c8-904a-465d-a79d-7fe359636bb4)

It is not pretty but it works and it saved me filament and printing effort. Using sanding paper or aceton to smooth the edge of the stripes to make a smooth transition between cams and stripes is not recommended as it ruins the positioning of the stripes and creates play on the axis again.

**Comment by RightRudderLeftStick** [comment]
Was it that the 608 bearings were loose in their sockets or in crooked? The part should be a snug enough fit that they are put in with a rubber mallet or pushing down with a wrench socket.

**Comment by freezir12** [comment]
The hole of the cams were to big (i guess as a result of ABS shrinkage, PETG was fine) That made the cams move on the bearings.

**Comment by RightRudderLeftStick** [comment]
Ah okay so it was a print issue.

I'm going to mark this issue as closed for now. But definitely post the completed build when you have it! 

Also if you haven't printed the top plate note there is a revision with an extra set of M5 holes which are for the damper piston configuration currently under development. 

https://www.youtube.com/shorts/R0IVPZbh21o

**Comment by RightRudderLeftStick** [comment]
closed - note for future build guides to mention the importance of insuring 603 bearings are straight in the cams

**Comment by freezir12** [comment]
I was not clear enough in my comment: 
Having the 603 bearings straight in the cams (very tight fit) did NOT solve the problem with the movement play on the yaw axis. Adding the stripes to the cams solved the issue for me. I am printing the pillow plate in PETG right now for further testing (had no other idea what to test)
